"""تحديث حقول نموذج البلاغ لدعم الحقول المتعددة

Revision ID: bee703eff51d
Revises: 
Create Date: 2025-03-15 01:42:42.978933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee703eff51d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('network_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('scammer_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('scammer_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('media_files',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('date_reported')
        batch_op.drop_column('network_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_provider', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_reported', sa.DATETIME(), nullable=True))
        batch_op.alter_column('media_files',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('scammer_phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('scammer_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('network_type')
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###
